source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'BaiSi' do

  use_frameworks!
  pod 'MJRefresh'
  pod 'MJExtension'
  pod 'SDWebImage', '~> 4.0.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'Masonry', '~> 1.0.2'
  pod 'SDCycleScrollView','~> 1.66'

end
